<a href="https://colab.research.google.com/github/stormmvanrooi/deep-learning-challenge/blob/branch001/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../content/charity_data.csv")
application_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning

bins = application_df['APPLICATION_TYPE'].value_counts()
bins

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(bins[bins<500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
bin_counts = application_df['CLASSIFICATION'].value_counts()

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
count_class = bin_counts[bin_counts>1]
count_class

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (bin_counts[bin_counts<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

   STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                       1.0                       0.0
1       1   108590  ...                       1.0                       0.0
2       1     5000  ...                       1.0                       0.0
3       1     6692  ...                       1.0                       0.0
4       1   142590  ...                       1.0                       0.0

[5 rows x 50 columns]

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

array([1, 1, 0, ..., 0, 1, 0])

In [11]:
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0859000e+05, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.6500179e+07, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

In [12]:
# Split the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [23]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=5
hidden_nodes_layer2=15
hidden_nodes_layer3=20

nn_model= tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 5)                 250

 dense_4 (Dense)             (None, 15)                90

 dense_5 (Dense)             (None, 1)                 16

=================================================================
Total params: 356
Trainable params: 356
Non-trainable params: 0
_________________________________________________________________

In [24]:
# Compile the model
nn_model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [25]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 2s 2ms/step - loss: 0.6195 - accuracy: 0.6772 - val_loss: 0.5704 - val_accuracy: 0.7292
Epoch 2/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5723 - accuracy: 0.7194 - val_loss: 0.5584 - val_accuracy: 0.7305
Epoch 3/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7197 - val_loss: 0.5545 - val_accuracy: 0.7302
Epoch 4/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7204 - val_loss: 0.5528 - val_accuracy: 0.7305
Epoch 5/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7215 - val_loss: 0.5530 - val_accuracy: 0.7300
Epoch 6/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7218 - val_loss: 0.5519 - val_accuracy: 0.7305
Epoch 7/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7284 - val_loss: 0.5514 - val_accuracy: 0.7367
Epoch 8/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7287 - val_loss: 0.5492 - val_accuracy: 0.7354
Epoch 9/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7286 - val_loss: 0.5515 - val_accuracy: 0.7292
Epoch 10/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5543 - accuracy: 0.7282 - val_loss: 0.5481 - val_accuracy: 0.7352
Epoch 11/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5535 - accuracy: 0.7296 - val_loss: 0.5490 - val_accuracy: 0.7341
Epoch 12/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7291 - val_loss: 0.5483 - val_accuracy: 0.7357
Epoch 13/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5529 - accuracy: 0.7289 - val_loss: 0.5479 - val_accuracy: 0.7354
Epoch 14/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7285 - val_loss: 0.5488 - val_accuracy: 0.7359
Epoch 15/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5523 - accuracy: 0.7291 - val_loss: 0.5471 - val_accuracy: 0.7354
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5521 - accuracy: 0.7293 - val_loss: 0.5475 - val_accuracy: 0.7341
Epoch 17/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5521 - accuracy: 0.7299 - val_loss: 0.5472 - val_accuracy: 0.7346
Epoch 18/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7297 - val_loss: 0.5472 - val_accuracy: 0.7357
Epoch 19/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7293 - val_loss: 0.5484 - val_accuracy: 0.7341
Epoch 20/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5514 - accuracy: 0.7293 - val_loss: 0.5495 - val_accuracy: 0.7334
Epoch 21/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7287 - val_loss: 0.5481 - val_accuracy: 0.7339
Epoch 22/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7287 - val_loss: 0.5470 - val_accuracy: 0.7334
Epoch 23/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7299 - val_loss: 0.5478 - val_accuracy: 0.7339
Epoch 24/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7309 - val_loss: 0.5462 - val_accuracy: 0.7331
Epoch 25/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7295 - val_loss: 0.5473 - val_accuracy: 0.7365
Epoch 26/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7303 - val_loss: 0.5481 - val_accuracy: 0.7370
Epoch 27/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7300 - val_loss: 0.5467 - val_accuracy: 0.7334
Epoch 28/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7297 - val_loss: 0.5474 - val_accuracy: 0.7352
Epoch 29/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5499 - accuracy: 0.7298 - val_loss: 0.5471 - val_accuracy: 0.7354
Epoch 30/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7299 - val_loss: 0.5469 - val_accuracy: 0.7346
Epoch 31/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7308 - val_loss: 0.5471 - val_accuracy: 0.7346
Epoch 32/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7305 - val_loss: 0.5471 - val_accuracy: 0.7352
Epoch 33/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7304 - val_loss: 0.5452 - val_accuracy: 0.7334
Epoch 34/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7302 - val_loss: 0.5461 - val_accuracy: 0.7334
Epoch 35/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7309 - val_loss: 0.5495 - val_accuracy: 0.7352
Epoch 36/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7305 - val_loss: 0.5471 - val_accuracy: 0.7341
Epoch 37/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7307 - val_loss: 0.5466 - val_accuracy: 0.7328
Epoch 38/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7300 - val_loss: 0.5467 - val_accuracy: 0.7336
Epoch 39/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7301 - val_loss: 0.5461 - val_accuracy: 0.7344
Epoch 40/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7308 - val_loss: 0.5457 - val_accuracy: 0.7352
Epoch 41/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7308 - val_loss: 0.5464 - val_accuracy: 0.7346
Epoch 42/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7317 - val_loss: 0.5466 - val_accuracy: 0.7352
Epoch 43/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7310 - val_loss: 0.5472 - val_accuracy: 0.7341
Epoch 44/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7307 - val_loss: 0.5461 - val_accuracy: 0.7326
Epoch 45/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7303 - val_loss: 0.5465 - val_accuracy: 0.7336
Epoch 46/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7310 - val_loss: 0.5461 - val_accuracy: 0.7336
Epoch 47/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7306 - val_loss: 0.5469 - val_accuracy: 0.7344
Epoch 48/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7307 - val_loss: 0.5463 - val_accuracy: 0.7339
Epoch 49/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7311 - val_loss: 0.5458 - val_accuracy: 0.7339
Epoch 50/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7316 - val_loss: 0.5458 - val_accuracy: 0.7336
Epoch 51/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7313 - val_loss: 0.5457 - val_accuracy: 0.7334
Epoch 52/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7313 - val_loss: 0.5474 - val_accuracy: 0.7336
Epoch 53/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7317 - val_loss: 0.5464 - val_accuracy: 0.7331
Epoch 54/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7317 - val_loss: 0.5471 - val_accuracy: 0.7334
Epoch 55/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7314 - val_loss: 0.5458 - val_accuracy: 0.7334
Epoch 56/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7314 - val_loss: 0.5464 - val_accuracy: 0.7354
Epoch 57/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7317 - val_loss: 0.5470 - val_accuracy: 0.7349
Epoch 58/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7310 - val_loss: 0.5448 - val_accuracy: 0.7326
Epoch 59/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7316 - val_loss: 0.5463 - val_accuracy: 0.7346
Epoch 60/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7310 - val_loss: 0.5463 - val_accuracy: 0.7336
Epoch 61/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7317 - val_loss: 0.5460 - val_accuracy: 0.7336
Epoch 62/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7316 - val_loss: 0.5459 - val_accuracy: 0.7331
Epoch 63/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7315 - val_loss: 0.5465 - val_accuracy: 0.7344
Epoch 64/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7318 - val_loss: 0.5461 - val_accuracy: 0.7341
Epoch 65/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7317 - val_loss: 0.5456 - val_accuracy: 0.7354
Epoch 66/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7316 - val_loss: 0.5463 - val_accuracy: 0.7349
Epoch 67/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7314 - val_loss: 0.5469 - val_accuracy: 0.7344
Epoch 68/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7318 - val_loss: 0.5460 - val_accuracy: 0.7336
Epoch 69/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7319 - val_loss: 0.5474 - val_accuracy: 0.7339
Epoch 70/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7318 - val_loss: 0.5475 - val_accuracy: 0.7352
Epoch 71/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7321 - val_loss: 0.5466 - val_accuracy: 0.7344
Epoch 72/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7319 - val_loss: 0.5482 - val_accuracy: 0.7326
Epoch 73/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7315 - val_loss: 0.5471 - val_accuracy: 0.7334
Epoch 74/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7314 - val_loss: 0.5454 - val_accuracy: 0.7339
Epoch 75/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7314 - val_loss: 0.5469 - val_accuracy: 0.7336
Epoch 76/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7322 - val_loss: 0.5473 - val_accuracy: 0.7346
Epoch 77/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7319 - val_loss: 0.5459 - val_accuracy: 0.7334
Epoch 78/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7319 - val_loss: 0.5475 - val_accuracy: 0.7331
Epoch 79/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7320 - val_loss: 0.5475 - val_accuracy: 0.7341
Epoch 80/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7314 - val_loss: 0.5467 - val_accuracy: 0.7346
Epoch 81/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7314 - val_loss: 0.5466 - val_accuracy: 0.7339
Epoch 82/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7321 - val_loss: 0.5462 - val_accuracy: 0.7331
Epoch 83/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7314 - val_loss: 0.5467 - val_accuracy: 0.7339
Epoch 84/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7318 - val_loss: 0.5479 - val_accuracy: 0.7349
Epoch 85/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7321 - val_loss: 0.5493 - val_accuracy: 0.7334
Epoch 86/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7322 - val_loss: 0.5467 - val_accuracy: 0.7346
Epoch 87/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7318 - val_loss: 0.5464 - val_accuracy: 0.7344
Epoch 88/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7321 - val_loss: 0.5459 - val_accuracy: 0.7344
Epoch 89/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7315 - val_loss: 0.5482 - val_accuracy: 0.7341
Epoch 90/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7322 - val_loss: 0.5456 - val_accuracy: 0.7352
Epoch 91/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7323 - val_loss: 0.5462 - val_accuracy: 0.7349
Epoch 92/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7323 - val_loss: 0.5461 - val_accuracy: 0.7349
Epoch 93/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7319 - val_loss: 0.5455 - val_accuracy: 0.7354
Epoch 94/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7321 - val_loss: 0.5470 - val_accuracy: 0.7346
Epoch 95/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7321 - val_loss: 0.5459 - val_accuracy: 0.7341
Epoch 96/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7322 - val_loss: 0.5466 - val_accuracy: 0.7362
Epoch 97/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7319 - val_loss: 0.5463 - val_accuracy: 0.7344
Epoch 98/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7321 - val_loss: 0.5458 - val_accuracy: 0.7344
Epoch 99/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7324 - val_loss: 0.5450 - val_accuracy: 0.7349
Epoch 100/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7325 - val_loss: 0.5481 - val_accuracy: 0.7331

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5535 - accuracy: 0.7297 - 760ms/epoch - 3ms/step
Loss: 0.5535045862197876, Accuracy: 0.72967928647995

In [22]:
# Export our model to HDF5 file
# Export our model to HDF5 file
from google.colab import files

nn_model.save('/content/Model_1.h5')
files.download('/content/Model_1.h5')